export const ARROW_TYPES = [
  {
    id: "normal",
    name: "Normal Arrow",
    key: "1",
    unlockTier: 1,
    armorInteraction: "chip",
    damage: 1,
    armorDamage: 1,
    primaryEffect: "Reliable single-target damage",
    bestAgainst: "Grunt, Runner, low armor enemies",
    economy: "Unlimited",
  },
  {
    id: "fire",
    name: "Fire Arrow",
    key: "2",
    unlockTier: 2,
    armorInteraction: "bypass",
    damage: 0,
    armorDamage: 0,
    burnDamagePerSecond: 0.35,
    burnDuration: 4,
    primaryEffect: "Bypasses armor and applies burning damage",
    bestAgainst: "Chainmail Guard, Brute, Siege Enemy",
    economy: "Arrow Charge",
  },
  {
    id: "piercing",
    name: "Piercing Arrow",
    key: "3",
    unlockTier: 3,
    armorInteraction: "line",
    damage: 1,
    armorDamage: 1,
    primaryEffect: "Line penetration through clustered enemies",
    bestAgainst: "Swarm, shield lines, packed waves",
    economy: "Limited ammo",
  },
  {
    id: "ice",
    name: "Ice Arrow",
    key: "4",
    unlockTier: 4,
    armorInteraction: "chip",
    damage: 0.5,
    armorDamage: 1,
    slowMultiplier: 0.45,
    slowDuration: 4,
    primaryEffect: "Slows enemy movement",
    bestAgainst: "Runner, Siege Enemy, boss adds",
    economy: "Cooldown or limited charge",
  },
  {
    id: "armorBreaker",
    name: "Armor Breaker",
    key: "5",
    unlockTier: 5,
    armorInteraction: "break",
    damage: 0.75,
    armorDamage: 3,
    primaryEffect: "Fast armor cracking",
    bestAgainst: "Chainmail, Shield Bearer, armored boss phases",
    economy: "Expensive ammo",
  },
  {
    id: "explosive",
    name: "Explosive Arrow",
    key: "6",
    unlockTier: 6,
    armorInteraction: "splash",
    damage: 1,
    armorDamage: 1,
    splashRadius: 70,
    primaryEffect: "Area damage around impact",
    bestAgainst: "Swarm, mixed low-HP waves",
    economy: "Rare ammo",
  },
  {
    id: "poison",
    name: "Poison Arrow",
    key: "optional",
    unlockTier: 7,
    armorInteraction: "status",
    damage: 0,
    armorDamage: 0,
    poisonDamagePerSecond: 0.2,
    poisonDuration: 8,
    primaryEffect: "Stacking damage over time",
    bestAgainst: "Brute, boss, slow high-HP enemies",
    economy: "Crafted or high shop cost",
  },
  {
    id: "volley",
    name: "Volley Shot",
    key: "skill",
    unlockTier: 8,
    armorInteraction: "current-arrow",
    damage: 0,
    armorDamage: 0,
    primaryEffect: "Shoots multiple arrows after a perfect word streak",
    bestAgainst: "Emergency cleanup, mixed waves",
    economy: "Combo or cooldown upgrade",
  },
];

export const ENEMY_TYPES = [
  {
    id: "grunt",
    name: "Grunt",
    firstAppears: "Levels 1-10",
    hp: 1,
    armor: 0,
    speed: 42,
    towerDamage: 4,
    rewardGold: 2,
    wordPattern: "Short common words",
    specialBehavior: "Basic enemy used to teach combat typing",
    recommendedCounter: "Normal Arrow",
    color: "#9CA3AF",
  },
  {
    id: "runner",
    name: "Runner",
    firstAppears: "Levels 11-20",
    hp: 1,
    armor: 0,
    speed: 68,
    towerDamage: 3,
    rewardGold: 3,
    wordPattern: "Short but frequent words",
    specialBehavior: "Reaches tower quickly and punishes slow switching",
    recommendedCounter: "Normal Arrow, Ice Arrow",
    color: "#F59E0B",
  },
  {
    id: "chainmailGuard",
    name: "Chainmail Guard",
    firstAppears: "Levels 21-30",
    hp: 1,
    armor: 3,
    speed: 34,
    towerDamage: 6,
    rewardGold: 7,
    wordPattern: "Medium words",
    specialBehavior: "Needs three normal hits to break armor, then one kill shot",
    recommendedCounter: "Fire Arrow, Armor Breaker",
    color: "#94A3B8",
  },
  {
    id: "shieldBearer",
    name: "Shield Bearer",
    firstAppears: "Levels 31-40",
    hp: 2,
    armor: 2,
    speed: 30,
    towerDamage: 7,
    rewardGold: 8,
    wordPattern: "Medium words with repeated letters",
    specialBehavior: "Reduces normal arrow damage unless hit with special arrows",
    recommendedCounter: "Piercing Arrow, Fire Arrow",
    color: "#2563EB",
  },
  {
    id: "swarm",
    name: "Swarm",
    firstAppears: "Levels 31-50",
    hp: 1,
    armor: 0,
    speed: 62,
    towerDamage: 2,
    rewardGold: 2,
    wordPattern: "Very short words",
    specialBehavior: "Many enemies spawn together; individual HP is low",
    recommendedCounter: "Piercing Arrow, Explosive Arrow",
    color: "#84CC16",
  },
  {
    id: "brute",
    name: "Brute",
    firstAppears: "Levels 41-60",
    hp: 5,
    armor: 1,
    speed: 24,
    towerDamage: 10,
    rewardGold: 12,
    wordPattern: "Longer words",
    specialBehavior: "High HP target that soaks time and forces target priority",
    recommendedCounter: "Fire Arrow, Poison Arrow",
    color: "#7C2D12",
  },
  {
    id: "bannerCaptain",
    name: "Banner Captain",
    firstAppears: "Levels 51-70",
    hp: 3,
    armor: 1,
    speed: 36,
    towerDamage: 8,
    rewardGold: 11,
    wordPattern: "Medium-long words",
    specialBehavior: "Adds temporary armor to nearby enemies",
    recommendedCounter: "Prioritize with Fire Arrow or Armor Breaker",
    color: "#9333EA",
  },
  {
    id: "siegeEnemy",
    name: "Siege Enemy",
    firstAppears: "Levels 61-80",
    hp: 4,
    armor: 2,
    speed: 22,
    towerDamage: 16,
    rewardGold: 14,
    wordPattern: "Long words",
    specialBehavior: "Deals heavy tower damage if it reaches the wall",
    recommendedCounter: "Ice Arrow, Fire Arrow, focused Normal Arrow",
    color: "#B45309",
  },
  {
    id: "fireResistantKnight",
    name: "Fire-Resistant Knight",
    firstAppears: "Levels 71-90",
    hp: 4,
    armor: 3,
    speed: 32,
    towerDamage: 11,
    rewardGold: 16,
    wordPattern: "Long words",
    specialBehavior: "Takes reduced burn damage, forcing alternate tactics",
    recommendedCounter: "Armor Breaker, Piercing Arrow",
    color: "#DC2626",
    burnResistance: 0.45,
  },
  {
    id: "boss",
    name: "Boss / Warlord",
    firstAppears: "Levels 10, 20, 50, 75, 100",
    hp: 18,
    armor: 4,
    speed: 18,
    towerDamage: 18,
    rewardGold: 50,
    wordPattern: "Phrase-length challenge words",
    specialBehavior: "Changes armor and summons adds by phase",
    recommendedCounter: "Mixed arrows; shop build matters",
    color: "#111827",
  },
];

export const ECONOMY_SOURCES = [
  { source: "Enemy kill", resource: "Gold", risk: "Low" },
  { source: "Perfect word", resource: "Gold + combo meter", risk: "Medium" },
  { source: "Enrichment phrase completion", resource: "Training Point", risk: "High" },
  { source: "Enrichment phrase streak", resource: "Temporary buff", risk: "High" },
  { source: "Tower HP remaining", resource: "Gold", risk: "Medium" },
  { source: "Level clear", resource: "Gold", risk: "Low" },
  { source: "Boss clear", resource: "Gold + Training Point", risk: "High" },
  { source: "Optional challenge phrase", resource: "Training Point + Arrow Charge", risk: "Very high" },
];

export const UPGRADE_SYSTEMS = [
  { id: "shop", name: "After-level shop", currency: "Gold" },
  { id: "training", name: "Training unlocks", currency: "Training Point" },
  { id: "arrowSwitching", name: "Combat arrow switching", currency: "Arrow Charge / ammo" },
  { id: "repair", name: "Emergency repair", currency: "Gold or cooldown" },
  { id: "typingMastery", name: "Typing mastery perks", currency: "Training Point" },
  { id: "milestone", name: "Milestone specialization", currency: "Gold + Training Point" },
];

export const TOWER_LEVELS = [
  { level: 1, name: "Sharpened Stakes", goldCost: 0, maxHp: 100, shield: 0, repair: "None", damageReduction: 0 },
  { level: 2, name: "Lashed Palisade", goldCost: 120, maxHp: 130, shield: 0, repair: "Repair option unlocked", damageReduction: 0 },
  { level: 3, name: "Cheval de Frise", goldCost: 220, maxHp: 170, shield: 20, repair: "End-level repair +10%", damageReduction: 0.05 },
  { level: 4, name: "Ironshod Cheval de Frise", goldCost: 380, maxHp: 220, shield: 40, repair: "End-level repair +15%", damageReduction: 0.1 },
  { level: 5, name: "Spiked Barricade", goldCost: 620, maxHp: 280, shield: 70, repair: "End-level repair +20%", damageReduction: 0.15 },
  { level: 6, name: "Iron Chevaux-de-Frise", goldCost: 900, maxHp: 350, shield: 100, repair: "Emergency shield once per level", damageReduction: 0.18 },
  { level: 7, name: "Barbed Rampart", goldCost: 1300, maxHp: 430, shield: 140, repair: "End-level repair +25%", damageReduction: 0.22 },
  { level: 8, name: "Dragonsteel Abatis", goldCost: 1800, maxHp: 520, shield: 200, repair: "Emergency shield + auto repair", damageReduction: 0.25 },
];

export const LONGBOWMAN_TIERS = [
  { tier: 1, weapon: "Longbow", unlock: "Start", goldCost: 0, trainingPointCost: 0, baseDamage: 1, attackSpeed: "Normal" },
  { tier: 2, weapon: "Reinforced Longbow", unlock: "Levels 11-20", goldCost: 180, trainingPointCost: 0, baseDamage: 1.25, attackSpeed: "Normal+" },
  { tier: 3, weapon: "Silver Bow", unlock: "Levels 21-40 + Training unlock", goldCost: 420, trainingPointCost: 2, baseDamage: 1.6, attackSpeed: "Fast" },
  { tier: 4, weapon: "Golden Bow", unlock: "Levels 41-70 + Training unlock", goldCost: 900, trainingPointCost: 4, baseDamage: 2.1, attackSpeed: "Fast+" },
  { tier: 5, weapon: "Royal Golden Bow", unlock: "Levels 71-90", goldCost: 1500, trainingPointCost: 6, baseDamage: 2.7, attackSpeed: "Very fast" },
  { tier: 6, weapon: "Fire Musket", unlock: "Final weapon / Levels 91-100", goldCost: 2400, trainingPointCost: 8, baseDamage: 4, attackSpeed: "Slow but heavy" },
];

export const LEVEL_TIER_CONFIGS = [
  { tier: 1, levels: "1-10", wordMin: 3, wordMax: 4, enemyCount: 10, spawnInterval: 2.8, maxAlive: 3, enemyIds: ["grunt"] },
  { tier: 2, levels: "11-20", wordMin: 4, wordMax: 5, enemyCount: 14, spawnInterval: 2.5, maxAlive: 4, enemyIds: ["grunt", "runner"] },
  { tier: 3, levels: "21-30", wordMin: 5, wordMax: 6, enemyCount: 18, spawnInterval: 2.25, maxAlive: 5, enemyIds: ["grunt", "runner", "chainmailGuard"] },
  { tier: 4, levels: "31-40", wordMin: 6, wordMax: 7, enemyCount: 22, spawnInterval: 2.05, maxAlive: 6, enemyIds: ["runner", "chainmailGuard", "shieldBearer", "swarm"] },
  { tier: 5, levels: "41-50", wordMin: 7, wordMax: 8, enemyCount: 27, spawnInterval: 1.9, maxAlive: 7, enemyIds: ["chainmailGuard", "shieldBearer", "swarm", "brute"] },
  { tier: 6, levels: "51-60", wordMin: 8, wordMax: 9, enemyCount: 32, spawnInterval: 1.75, maxAlive: 8, enemyIds: ["shieldBearer", "brute", "bannerCaptain"] },
  { tier: 7, levels: "61-70", wordMin: 9, wordMax: 10, enemyCount: 38, spawnInterval: 1.6, maxAlive: 8, enemyIds: ["brute", "bannerCaptain", "siegeEnemy"] },
  { tier: 8, levels: "71-80", wordMin: 10, wordMax: 11, enemyCount: 44, spawnInterval: 1.45, maxAlive: 9, enemyIds: ["bannerCaptain", "siegeEnemy", "fireResistantKnight"] },
  { tier: 9, levels: "81-90", wordMin: 11, wordMax: 12, enemyCount: 52, spawnInterval: 1.3, maxAlive: 10, enemyIds: ["siegeEnemy", "fireResistantKnight", "brute"] },
  { tier: 10, levels: "91-100", wordMin: 12, wordMax: 14, enemyCount: 64, spawnInterval: 1.12, maxAlive: 12, enemyIds: ["fireResistantKnight", "siegeEnemy", "boss"] },
];

export const ENRICHMENT_PHRASES = [
  { phrase: "practice makes perfect", reward: 1 },
  { phrase: "actions speak louder than words", reward: 2 },
  { phrase: "knowledge is power", reward: 2 },
  { phrase: "slow and steady wins the race", reward: 2 },
  { phrase: "fortune favors the brave", reward: 2 },
  { phrase: "a stitch in time saves nine", reward: 3 },
  { phrase: "the pen is mightier than the sword", reward: 3 },
  { phrase: "where there is a will there is a way", reward: 4 },
];

export const WORDS = [
  "ace", "act", "air", "ant", "arch", "arrow", "armor", "battle", "brave", "bow", "castle", "chain", "charge",
  "combat", "defend", "dragon", "eagle", "enemy", "field", "flame", "focus", "gold", "guard", "hero",
  "honor", "ice", "iron", "knight", "lance", "legend", "longbow", "march", "mason", "perfect", "pierce",
  "practice", "quiver", "runner", "shield", "silver", "steady", "storm", "tower", "training", "victory",
  "watchtower", "wilderness", "knowledge", "reinforced", "magnificent", "nevertheless", "portcullis",
  "trustworthy", "stronghold", "battlement", "apprentice", "atmosphere", "drawbridge", "resistance",
  "tournament", "firestorm", "crossbowman", "fortification", "understanding", "extraordinary",
  "counterattack", "responsibility", "transformation", "misunderstanding",
];

export function getLevelTier(level) {
  return Math.max(1, Math.min(10, Math.ceil(level / 10)));
}

export function getLevelConfig(level) {
  return LEVEL_TIER_CONFIGS[getLevelTier(level) - 1];
}

export function getWordLengthRange(level) {
  const config = getLevelConfig(level);
  return { min: config.wordMin, max: config.wordMax };
}

export function getArrowType(id) {
  return ARROW_TYPES.find((arrow) => arrow.id === id);
}

export function getEnemyType(id) {
  return ENEMY_TYPES.find((enemy) => enemy.id === id);
}
